/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package local.ytk.java.programgenerator;

public class ProgramGenerator {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new ProgramGenerator().getGreeting());
    }
}
