/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package local.ytk.java.programgenerator;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        ProgramGenerator classUnderTest = new ProgramGenerator();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
